links:
  - text: 'BLOG'
    href: '/?post'
  - text: 'REPOSITORY'
    href: 'https://github.com/shotatanakait/cms'
  - text: 'PORTFOLIO'
    href: '/?post=portfolio'

sociallinks:
  - icon: 'fa-square-twitter'
    href: 'https://twitter.com/nakasho0619'
    style: 'style="color: #4284f5;"'
  - icon: 'fa-instagram'
    href: 'https://www.instagram.com/shotatanakait/'
    style: 'style="color: #6d0f80;"'
  - icon: 'fa-square-github'
    href: 'https://github.com/shotatanakait'
    style: 'style="color: #222e3f;"'
  - icon: 'fa-youtube'
    href: 'https://www.youtube.com/@shotatanakait'
    style: 'style="color: #c61527;"'

